import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {
  FacebookTrackingProvider,
  FacebookPageView,
} from 'next-facebook-tracking/components'
import {facebook} from './facebook'

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FacebookTrackingProvider client={facebook}>
          {children}
          <FacebookPageView />
        </FacebookTrackingProvider>
      </body>
    </html>
  )
}
